### PR TITLE
Changed out Assets so that they are the same size

### PR DESCRIPTION
**Pull request by Patrick-Woelfle**
I changed out all the assets, so that they have the same pixel size.
Now when adding new assets, they should fit into the scene, as long as they aren't scaled.
I also added a tile map based System based on TileMapLayer-Node the for the background to make it easier to change, added a temporary sprite for the enemies and tidied up the repository structure for the assets.
I made sure that everything still works, however the range of attacks, speed of characters and how close to you enemies stop seems different because everything is a lot smaller.

### CODE REVIEW

**Comment by Patrick-Woelfle** [comment]
(Ich update das Formatting und reverse die Test Commits morgen noch)

**Comment by Patrick-Woelfle** [comment]
All the Issues have been fixed and now the speeds are actually fitting again.
There's still one error message regarding navigation, but i don't know where it's coming from and it doesn't seem to influence anything

**Comment by Leo-Dev-2004** [comment]
is the ally supposed to be this fast?

**Comment by Leo-Dev-2004** [comment]
the assets look very good, but is there a CORE or what about the healing circles that are currently in main?

**Review by konradbausch — CHANGES_REQUESTED** [review]
Looks good now, but now there is a problem, where the character is very jittery when moving for some reason. This needs to be looked into before merging. Maybe has something to do with the engine not handling smaller scale so well, but not sure.

**Comment by Patrick-Woelfle** [comment]
I tried a lot but the jittering hasn't gone away, so i just scaled everything by 4 and now it's about as noticable as on the main branch.
It's only an Issue when the camera is moving, so it can probably only be fixed by customizing the camera, but for now this works.
Regarding new changes with the core, i made another Pull Request, so that i can update the assets branch without merging it directly onto main
(which i will hopefully be able to complete tomorrow)

**Comment by Patrick-Woelfle** [comment]
Thanks for fixing the jittering ^ ^

**Comment by Patrick-Woelfle** [comment]
Merging into main was to complicated, so i just made a new branch off of main and repeated the changes there

**Pull request closed without merging**
