### PR TITLE
Working health system and item branch -> current main

### LINKED ISSUE #5: Missing core implementation
Currently the core with very basic functionality is missing which we need for implementing the Map functionality

### LINKED ISSUE #6: [Leo] Schattengegner
- [x] For enemies we need HP and a HP bar. Konrad rewrote an existing plugin which should kinda work now

- [x] - Schattenwesen folgen und gehen direkt zu nächsten Entity (ohne Abstand) und ziehen pro Sekunde 10 LP für Arbeitertyp und -5 LP für Soldatentyp ab.
- [x] - Schattenwesen spawnen random und laufen zum Spieler, wenn in der Nähe von Core.
- [ENTFERNT] - Schattenwesen sind unsichtbar, wenn sie nicht in der Nähe von irgendeinem Allie oder Spieler sind.

### PR DESCRIPTION
**Pull request by Leo-Dev-2004**
Resolves #5 
Resolves #6 

@xSouperMan and me implemented the items branch into the Health system branch. We want to merge it into main so that the others can work with it ASAP

### CODE REVIEW

**Comment by Benzooos** [comment]
2024-11-2618-41-28-ezgif com-video-to-gif-converter

At the beginning there is an invisible enemy that attacks the player and the ally. It has no visible pathfinding line. Is this intended? Rest of the code looks nice and works on my machine. Great Job!

**Comment by konradbausch** [comment]
I removed the invisible Enemy
Also made it so the Enemy Manager doesnt need threading, since it made things more complicated than it needed to be.

**Review by konradbausch — APPROVED** [review]

**Comment by Leo-Dev-2004** [comment]
Cant review anymore but 2 reviews are required. :/

**Review by Malu010 — APPROVED** [review]
LGTM

**Comment by Leo-Dev-2004** [comment]
> 2024-11-2618-41-28-ezgif com-video-to-gif-converter (2) [ 2024-11-2618-41-28-ezgif com-video-to-gif-converter (2) ](https://private-user-images.githubusercontent.com/148370955/390085324-0e65e995-4a54-4bca-b1b1-ff377aee4a6a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTYzMTgsIm5iZiI6MTczMjY1NjAxOCwicGF0aCI6Ii8xNDgzNzA5NTUvMzkwMDg1MzI0LTBlNjVlOTk1LTRhNTQtNGJjYS1iMWIxLWZmMzc3YWVlNGE2YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQyMTIwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGIzMDhkNTA3NzczMTI1Zjg3YTMyMzAzN2I5ZGJmN2IyOWM0ODZhNmFkYjRhYzE4OTRiNWE3MjA5MzQ4ZmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OpVAxAE7hcs60fOoIFhPpMVaZ4zDz6UUUa5SNM_xz70) [ ](https://private-user-images.githubusercontent.com/148370955/390085324-0e65e995-4a54-4bca-b1b1-ff377aee4a6a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTYzMTgsIm5iZiI6MTczMjY1NjAxOCwicGF0aCI6Ii8xNDgzNzA5NTUvMzkwMDg1MzI0LTBlNjVlOTk1LTRhNTQtNGJjYS1iMWIxLWZmMzc3YWVlNGE2YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQyMTIwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGIzMDhkNTA3NzczMTI1Zjg3YTMyMzAzN2I5ZGJmN2IyOWM0ODZhNmFkYjRhYzE4OTRiNWE3MjA5MzQ4ZmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OpVAxAE7hcs60fOoIFhPpMVaZ4zDz6UUUa5SNM_xz70)
> 
> At the beginning there is an invisible enemy that attacks the player and the ally. It has no visible pathfinding line but has a hitbox. Is this intended? Rest of the code looks nice and works on my machine. Great Job!

Nope, not intended. I initially thought Konrad had added some kind of collision damage system. XD

**Review by Malu010 — APPROVED** [review]

**Pull request merged**
